x = int(input("Enter the number of students in the first group : "))
y = int(input("Enter the number of students in the second group : "))
z = int(input("Enter the number of students in the third group : "))
X = int((x//2)+(x%2))
Y = int((y//2)+(y%2))
Z = int((z//2)+(z%2))
print(X + Y + Z)
input()
